# -*- coding: utf-8 -*-
"""PersonaSync.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cJmJ_O7PTMMTKDdiDuj82O3RK8qUhtjY
"""

!pip install insightface opencv-python scikit-learn numpy onnxruntime

# ---------- Imports ----------
import os
import cv2
import numpy as np
from insightface.app import FaceAnalysis

# ---------- 1. Initialize InsightFace ----------
app = FaceAnalysis(name="buffalo_l")
app.prepare(ctx_id=0)  # GPU (use -1 for CPU)

# ---------- 2. Utility Functions ----------

def read_image(path):
    """Read image and convert to RGB"""
    img = cv2.imread(path)
    return cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

def normalize(v):
    """L2 normalize vector"""
    return v / np.linalg.norm(v)

# ---------- 3. Extract faces + embeddings (FACE-LEVEL) ----------

def extract_faces_and_embeddings(image):
    faces = app.get(image)
    results = []

    for i, face in enumerate(faces):
        if not is_face_good_quality(image, face.bbox):
            print(f"⚠️ Skipping face {i} (low quality)")
            continue

        emb = face.embedding
        emb = emb / np.linalg.norm(emb)

        results.append({
            "face_index": i,
            "embedding": emb,
            "bbox": face.bbox
        })

    return results

# ---------- 4. Main ML Logic (MEMORY-SPACE SAFE) ----------

MATCH_THRESHOLD = 0.45  # IMPORTANT (real-world photos)

def process_image_in_memory_space(image, person_stats):
    """
    image          : RGB image
    person_stats   : {
        person_id: {
            centroid: np.array,
            count: int
        }
    }
    """
    faces = extract_faces_and_embeddings(image)
    results = []

    for face in faces:
        emb = face["embedding"]

        best_person = None
        best_score = -1

        # Try matching existing personas
        for pid, data in person_stats.items():
            score = np.dot(emb, data["centroid"])
            if score > best_score:
                best_score = score
                best_person = pid

        if best_score >= MATCH_THRESHOLD:
            # SAME PERSON → update centroid
            data = person_stats[best_person]
            data["centroid"] = (
                data["centroid"] * data["count"] + emb
            ) / (data["count"] + 1)
            data["count"] += 1
            person_id = best_person
        else:
            # NEW PERSON
            person_id = f"person_{len(person_stats)}"
            person_stats[person_id] = {
                "centroid": emb,
                "count": 1
            }

        results.append({
            "face_index": face["face_index"],
            "person_id": person_id,
            "confidence": round(best_score, 3)
        })

    return results, person_stats

#face quality check
def is_face_good_quality(image, bbox):
    x1, y1, x2, y2 = map(int, bbox)

    h, w, _ = image.shape
    x1, y1 = max(0, x1), max(0, y1)
    x2, y2 = min(w, x2), min(h, y2)

    face = image[y1:y2, x1:x2]
    if face.size == 0:
        return False

    # --- Size check ---
    fh, fw, _ = face.shape
    if fh < 50 or fw < 50:
        return False

    gray = cv2.cvtColor(face, cv2.COLOR_RGB2GRAY)

    # --- Blur check ---
    blur = cv2.Laplacian(gray, cv2.CV_64F).var()
    if blur < 80:          # ⬆️ stricter than before
        return False

    # --- Brightness check (CRITICAL for your images) ---
    brightness = np.mean(gray)
    if brightness < 60:    # ⬆️ MOST IMPORTANT
        return False
    if brightness > 220:
        return False

    # --- Contrast check (new) ---
    contrast = gray.std()
    if contrast < 25:      # silhouettes fail here
        return False

    return True

#DRAW BOXES + PERSON ID ON IMAGE
import matplotlib.pyplot as plt

def visualize_faces(image, results, title=""):
    """
    image   : RGB image
    results : output from process_image_in_memory_space
    """
    faces = app.get(image)

    img_copy = image.copy()

    for face, res in zip(faces, results):
        x1, y1, x2, y2 = map(int, face.bbox)
        person_id = res["person_id"]

        # Draw rectangle
        cv2.rectangle(img_copy, (x1, y1), (x2, y2), (0, 255, 0), 2)

        # Put text
        cv2.putText(
            img_copy,
            person_id,
            (x1, y1 - 10),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.6,
            (255, 0, 0),
            2
        )

    plt.figure(figsize=(6, 6))
    plt.imshow(img_copy)
    plt.title(title)
    plt.axis("off")
    plt.show()

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from collections import defaultdict

# ---------- Storage ----------
person_faces = defaultdict(list)

TEST_DIR = "/content/test_images"
person_stats = {}  # ONE memory space

print("\n🚀 Starting ML Test...\n")

# ---------- Process each image ----------
for img_name in sorted(os.listdir(TEST_DIR)):
    img_path = os.path.join(TEST_DIR, img_name)
    image = read_image(img_path)

    print(f"\n📸 Processing: {img_name}")

    results, person_stats = process_image_in_memory_space(
        image,
        person_stats
    )

    for r in results:
        print(
            f"  Face {r['face_index']} → {r['person_id']} "
            f"(confidence={r['confidence']})"
        )

    # --- Extract faces again for visualization ---
    faces = app.get(image)

    # --- Draw boxes + store crops ---
    img_copy = image.copy()

    for face, res in zip(faces, results):
        x1, y1, x2, y2 = map(int, face.bbox)

        # clamp bbox to image size
        h, w, _ = image.shape
        x1, y1 = max(0, x1), max(0, y1)
        x2, y2 = min(w, x2), min(h, y2)

        crop = image[y1:y2, x1:x2]
        person_faces[res["person_id"]].append(crop)

        # draw box
        cv2.rectangle(img_copy, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.putText(
            img_copy,
            res["person_id"],
            (x1, y1 - 10),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.6,
            (255, 0, 0),
            2
        )

    # --- Show annotated image ---
    plt.figure(figsize=(6, 6))
    plt.imshow(img_copy)
    plt.title(img_name)
    plt.axis("off")
    plt.show()

# ---------- Final per-person face collections ----------
print("\n✅ FINAL PERSONA FACE GROUPS")

for person_id, crops in person_faces.items():
    print(f"\n🟢 {person_id} ({len(crops)} faces)")

    plt.figure(figsize=(12, 3))
    for i, crop in enumerate(crops):
        plt.subplot(1, len(crops), i + 1)
        plt.imshow(crop)
        plt.axis("off")
    plt.show()